### ISSUE TITLE
Read buffer into user-provided `Vec`

### ISSUE THREAD

**Issue by AdrianEddy** [UpsettingBoy/gpgpu-rs#8]
Is there a way to read data from GPU buffer into user-provided buffer? Looks like currently `read()` function returns `Vec`, thus allocating new memory every time. Same for Image buffers

**Comment by jeronimosg** [comment]
Not right now. I didn't consider that previously, but it's a good point. I'll look into that 😅

**Comment by jeronimosg** [comment]
Thanks to some API changes, this is solved with #9.

**Comment by AdrianEddy** [comment]
nice! thank you 😀
